name: Turkiz
type: division
environments:
  dev: {}
  ppd:
    shared_services:
      networking:
        untrusted:
          - name: "hub1"
            resource_group_name: "turkiz-untrusted-ppd-hub1-rg"
            resource_group_tags:
              env: "ppd"
              division: "turkiz"
            virtual_network_name: "turkiz-untrusted-ppd-hub1"
            virtual_network_address_space: "10.113.3.0/24"
            dns_servers: []
            subnets:
              palo:
                address_prefixes:
                  - 10.113.3.0/28
            route_tables:
              udr-turkiz-untrusted-ppd-hub1:
                route_name: "default-route"
                destination_prefix: "0.0.0.0/0"
                next_hop_type: "VirtualAppliance"
                next_hop_ip: "1.1.1.1"
            firewall_config:
              name: "turkiz-untrusted-ppd-hub1-fw"
              sku_name: "AZFW_Hub"
              sku_tier: "Standard"
              threat_intel_mode: "Alert"
              private_ip_ranges: []
              zones: ["1", "2", "3"]
              public_ip_allocation_method: "Static"
              public_ip_sku: "Standard"
              subnet_address_prefix: "10.113.3.64/26"
              tags:
                env: "ppd"
                division: "turkiz"
        trusted:
          - name: "hub1"
            resource_group_name: "turkiz-trusted-ppd-hub1-rg"
            resource_group_tags:
              env: "ppd"
              division: "turkiz"
            virtual_network_name: "turkiz-trusted-ppd-hub1"
            virtual_network_address_space: "10.113.2.0/24"
            dns_servers: []
            subnets:
              palo:
                address_prefixes:
                  - 10.113.2.0/28
            route_tables:
              udr-turkiz-trusted-ppd-hub1:
                route_name: "default-route"
                destination_prefix: "0.0.0.0/0"
                next_hop_type: "VirtualAppliance"
                next_hop_ip: "1.1.1.1"
            firewall_config:
              name: "turkiz-trusted-ppd-hub1-fw"
              sku_name: "AZFW_Hub"
              sku_tier: "Standard"
              zones: ["1", "2", "3"]
              public_ip_allocation_method: "Static"
              public_ip_sku: "Standard"
              subnet_address_prefix: "10.113.2.64/26"
              tags:
                env: "ppd"
                division: "turkiz"
  prd:
    shared_services:
      networking:
        untrusted:
          - name: "hub1"
            resource_group_name: "turkiz-untrusted-prd-hub1-rg"
            resource_group_tags:
              env: "prd"
              division: "turkiz"
            virtual_network_name: "turkiz-untrusted-prd-hub1"
            virtual_network_address_space: "10.113.1.0/24"
            dns_servers: []
            subnets:
              palo:
                address_prefixes:
                  - 10.113.1.0/28
            route_tables:
              udr-turkiz-untrusted-prd-hub1:
                route_name: "default-route"
                destination_prefix: "0.0.0.0/0"
                next_hop_type: "VirtualAppliance"
                next_hop_ip: "1.1.1.1"
            firewall_config:
              name: "turkiz-untrusted-prd-hub1-fw"
              sku_name: "AZFW_Hub"
              sku_tier: "Standard"
              zones: ["1", "2", "3"]
              public_ip_allocation_method: "Static"
              public_ip_sku: "Standard"
              subnet_address_prefix: "10.113.1.64/26"
              tags:
                env: "prd"
                division: "turkiz"
        trusted:
          - name: "hub1"
            resource_group_name: "turkiz-trusted-prd-hub1-rg"
            resource_group_tags:
              env: "prd"
              division: "turkiz"
            virtual_network_name: "turkiz-trusted-prd-hub1"
            virtual_network_address_space: "10.113.0.0/24"
            dns_servers: []
            subnets:
              palo:
                address_prefixes:
                  - 10.113.0.0/28
            route_tables:
              udr-turkiz-trusted-prd-hub1:
                route_name: "default-route"
                destination_prefix: "0.0.0.0/0"
                next_hop_type: "VirtualAppliance"
                next_hop_ip: "1.1.1.1"
            firewall_config:
              name: "turkiz-trusted-prd-hub1-fw"
              sku_name: "AZFW_Hub"
              sku_tier: "Standard"
              zones: ["1", "2", "3"]
              public_ip_allocation_method: "Static"
              public_ip_sku: "Standard"
              subnet_address_prefix: "10.113.0.64/26"
              tags:
                env: "prd"
                division: "turkiz"
