hubs:
  internet-prod:
    resource_group_name: "internet-prod-rg"
    resource_group_location: "Israel Central"
    resource_group_tags:
      env: "prod"
      team: "network"
    virtual_network_name: "internet-prod-hub"
    virtual_network_address_space: "10.112.4.0/24"
    dns_servers: []
    subnets:
      GatewaySubnet:
        address_prefixes:
          - 10.112.4.0/28

  on-prem:
    resource_group_name: "on-prem-rg"
    resource_group_location: "Israel Central"
    resource_group_tags:
      env: "onprem"
      team: "network"
    virtual_network_name: "on-prem-hub"
    virtual_network_address_space: "10.112.3.0/24"
    dns_servers: []
    subnets: {}